# Generated by Django 4.2 on 2023-08-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='manager',
        ),
    ]
