# Generated by Django 4.2 on 2023-08-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_place_latitude_alter_place_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='My',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
            ],
        ),
    ]
