# Generated by Django 4.2 on 2023-08-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_recomment_post_alter_recomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='mine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recomment',
            name='mine',
            field=models.BooleanField(default=False),
        ),
    ]
