# Generated by Django 4.2 on 2023-08-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_comment_mine_remove_post_mine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='mine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recomment',
            name='mine',
            field=models.BooleanField(default=False),
        ),
    ]
