# Generated by Django 4.2 on 2023-08-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment_mine_post_mine_recomment_mine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='mine',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mine',
        ),
        migrations.RemoveField(
            model_name='recomment',
            name='mine',
        ),
    ]
